Insert into groups values('advocacy2017','advocacy','43','ADvocacy is a student group committed to social justice and provision of humanitarian assistance to marginalized communities throughout Abu Dhabi.');
Insert into groups values('anchorage2012','anchorage society','40','A safe place where students of all sexual orientations and gender expressions can come to teach, learn, and dialogue. Devoted to the principles of respect, social equality, and inclusion.');
Insert into groups values('africa2006','africa global','55','At Africa Global, we celebrate our wonderfully diverse mosaic of cultural identities and heritage across the continent and its diaspora, but more importantly we hope to help bring about new friendships, consolidate already existing ones and have semesters full of learning, fun and meaningful events. ');
Insert into groups values('blockchain2008','blockchain collective','47','Blockchains are the future. Here at Blockchain Collective we aim to educate ourselves and get ahead with the world that is dynamically changing to adapt this innovation.');
Insert into groups values('BPM2017','BPM','36','BPM is a place for members of the NYUAD community who share a passion for DJing to practice their art.');
Insert into groups values('capoeira2011','capoeira club','40','Capoeira is an Afro-Brazilian martial art which incorporates elements of dance and acrobatics.');
Insert into groups values('catholic2005','catholic community','41','The Catholic SIG aims to create a community that strengthens spiritual Catholic life and faith through prayer, dialogue and understanding of Catholicism, and apostolate.');
Insert into groups values('chinese2006','chinese culture club','50','This club is dedicated to promoting the Chinese culture among the NYU Abu Dhabi community.');
Insert into groups values('discovr2002','discovr','49','We are a SIG devoted to learning and promoting Virtual Reality (VR) and Augmented Reality(AR) technologies through research and development. ');
Insert into groups values('ecoherence2016','ecoherence','22','Ecoherence transforms the wider NYU Abu Dhabi community into agents for sustainability and environmental social justice.');
Insert into groups values('equestrian2015','equestrian','37','We are a group of students who are passionate and fully committed to horseback-riding.');
Insert into groups values('hackad2012','hackad','38','We promote sharing knowledge, learning as a community and writing beautiful, concise code.');
Insert into groups values('marketing2015','marketing','23','The Marketing Society aims to create and connect marketers within Abu Dhabi and beyond. ');
Insert into groups values('oh2002','oh shoot!','22','A group of students meeting to learn and practice archery, the ancient art of shooting with a bow and arrow, thereby developing skills of patience, focus and mental as well as physical strength');
Insert into groups values('paused:2015','paused: videogame society','32','PAUSED focuses on creating a fun and exciting atmosphere where you can take a break and pause the stress in your life by playing video games and board games with others.');
Insert into groups values('spacious2016','spacious','36','Spacious is a community of people who want to learn and practice mindfulness and compassion. ');
Insert into groups values('strip2015','strip club','49','We deal with almost all things animated and works that carefully combine image and text. ');
Insert into groups values('students2017','students for justice in palestine','41','The mission of SJP is to provide forums to raise awareness of Palestinian human, economic, political, social, and cultural rights.');
Insert into groups values('design2017','design collective','36','We are a student-powered, project-driven group that seeks to institute great design in our world. ');
Insert into groups values('tower2016',' of babel','43','A SIG for those of us who love linguistics and who want to learn new languages by making friends from all over the world');
Insert into groups values('veggie2012','veggie might','33','Veggie Might is dedicated to promoting vegan lifestyles and animal rights in the NYUAD community.');
Insert into groups values('weSTEM2007','weSTEM','38','weSTEM (Women Empowered in STEM) is established in order to increase the number of girls and women pursuing degrees and careers in science, technology, engineering and mathematics ');
Insert into groups values('woodworking2013','woodworking','32','Are you interested in learning a hard skill and working with your hands? Have you always wanted to use power tools and never had an excuse before?');
Insert into groups values('coffee2010','coffee collective','33','The Coffee Collective is interested in coffee craft and bringing people together around coffee.');
Insert into groups values('tashan2012','tashan','43','TASHAN is the South Asian SIG. We aim to spread awareness and understanding of South Asian culture and heritage in the NYUAD community.');
